Repository prgrms-fe-devcourse/FEDC3_Tripend_JAEHO, pull requests merged in 2023-04, with the labels that each got.

#164 refactor: 동우 폴더 구조 변경
  src/components/Auth/Signin/index.jsx
  src/components/Auth/Signin/style.js
  src/components/Auth/Signup/index.jsx
  src/components/Auth/Signup/style.js
  src/components/MyHome/index.jsx
  src/hooks/useSigninForm.js
  src/hooks/useSignupForm.js
  src/pages/SigninPage/index.jsx
  src/pages/SignupPage/index.jsx
Labels: refactor

#167 refactor: mypage에 분리된 hook 합치기
  src/Router.jsx
  src/components/MyHome/UserInfo/index.jsx
  src/components/MyHome/UserPoster/index.jsx
  src/components/MyHome/index.jsx
  src/components/UploadImage/index.jsx
  src/components/UserPageSidebar/index.jsx
  src/components/UserPageSidebar/style.js
  src/hooks/useGetMyHomeUserInfo.js
  src/hooks/useMyhomeUploadFile.js
  src/hooks/useNewPassWordForm.js
  src/hooks/usePoster.js
  src/pages/MyPosterPage/index.jsx
  src/pages/MySettingPage/index.jsx
Labels: refactor

#166 refactor: main page에 분리된 hook 합치기
  src/components/ChannelList/index.jsx
  src/components/MainSection/Like/index.jsx
  src/components/MainSection/PostDetail/Comments/index.jsx
  src/components/MainSection/index.jsx
  src/hooks/useChannel.js
  src/hooks/useComment.js
  src/hooks/useLike.js
  src/hooks/useMainSection.js
Labels: refactor

#168 hotfix: 경로 설정
  src/components/MyHome/index.jsx
Labels: hotFix

#170 chore: Vite 마이그레이션
  .babelrc
  .env.example
  index.html
  package-lock.json
  package.json
  postcss.config.js
  public/assets/Location.png
  public/assets/Logo.svg
  public/assets/logo.png
  public/assets/smile_emoji.png
  public/assets/upload.svg
  public/favicon.ico
  src/apis/core/index.js
  src/components/AddPost/AddPostForm/index.jsx
  src/components/Common/Icons/AddPostIcon.jsx
  src/components/Common/Icons/Alarm.jsx
  src/components/Common/Icons/Logout.jsx
  src/components/MainSection/PostDetail/Comments/index.jsx
  src/components/MainSection/PostDetail/index.jsx
  src/components/MainSection/index.jsx
  src/components/Pagination/index.jsx
  src/components/UploadImage/index.jsx
  src/hooks/usePostDetail.js
  src/main.jsx
  src/pages/Header/index.jsx
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: chore

#178 refactor: User component ts로 마이그레이션
  src/components/User/UserInfo/index.tsx
  src/components/User/UserInfo/style.ts
  src/components/User/UserPageSidebar/index.tsx
  src/components/User/UserPageSidebar/style.ts
  src/components/User/UserPost/Pagination/index.tsx
  src/components/User/UserPost/Pagination/style.ts
  src/components/User/UserPost/UserPosteItem/index.tsx
  src/components/User/UserPost/UserPosteItem/style.ts
  src/components/User/UserPost/UserPosteItem/type.ts
  src/components/User/UserPost/style.ts
  src/components/User/UserSettingPassword/index.tsx
  src/components/User/UserSettingPassword/style.ts
  src/components/User/UserSidebar/UserList/index.tsx
  src/components/User/UserSidebar/UserList/style.ts
  src/components/User/UserSidebar/UserSearchBar/index.tsx
  src/components/User/UserSidebar/UserSearchBar/style.ts
  src/components/User/UserSidebar/index.tsx
  src/components/User/UserSidebar/style.ts
  src/components/User/UserSidebar/type.ts
Labels: refactor

#177 Auth 폴더 타입스크립트 마이그레이션
  src/apis/auth.ts
  src/apis/core/index.ts
  src/components/Auth/RequireAuth/index.tsx
  src/components/Auth/Signin/index.tsx
  src/components/Auth/Signin/style.ts
  src/components/Auth/Signup/index.tsx
  src/components/Auth/Signup/style.ts
  src/recoil/authState.ts
  src/types/auth/auth.interfaces.ts
  src/utils/constants/auth.ts
  src/utils/storage.js
  src/utils/storage.ts
  src/utils/validate/signup.ts
Labels: refactor

#183 refactor: Like 컴포넌트 타입스크립트 마이그레이션
  package-lock.json
  package.json
  src/apis/alarm.ts
  src/apis/like.ts
  src/components/Post/Like/index.tsx
  src/components/Post/Like/style.ts
  src/components/Post/PostDetail/index.jsx
  src/recoil/postStates.ts
  src/utils/constants/alarm.ts
  src/utils/constants/post.ts
  src/utils/storage.ts
  src/vite-env.d.ts
Labels: refactor

#186 refactor: Skeleton 타입스크립트 마이그레이션
  src/components/Common/Skeleton/Base.tsx
  src/components/Common/Skeleton/Box.tsx
  src/components/Common/Skeleton/Card.tsx
  src/components/Common/Skeleton/Circle.tsx
  src/components/Common/Skeleton/Detail.tsx
  src/components/Common/Skeleton/Paragraph.tsx
  src/components/Common/Skeleton/index.tsx
  src/components/Common/Skeleton/type.ts
Labels: refactor

#190 refactor: Icons 컴포넌트 타입스크립트 마이그레이션
  src/components/Common/Icons/AddPostIcon.tsx
  src/components/Common/Icons/Alarm.tsx
  src/components/Common/Icons/Badge.tsx
  src/components/Common/Icons/Logout.tsx
  src/components/Common/Icons/index.ts
Labels: refactor

#194 refactor: Avatar & Image 컴포넌트 타입스크립트 마이그레이션
  src/components/Common/Avatar/index.tsx
  src/components/Common/Image/index.tsx
Labels: refactor

#192 refactor: button 컴포넌트 타입스크립트 마이그레이션
  src/components/Common/Button/index.tsx
Labels: refactor
