Repository prgrms-fe-devcourse/FEDC3_Tripend_JAEHO, pull requests merged in 2023-01, with the labels that each got.

#12 Feat/modal
  src/apis/post.js
  src/components/Modal/index.jsx
  src/components/Modal/style.js
  src/components/trips/index.jsx
  src/hooks/useClickAway.js
  src/index.jsx
  src/recoil/RecoilPostStates.js
  src/recoil/RecoilToggleStates.js
Labels: feature

#14 feat/signup
  package-lock.json
  package.json
  src/apis/auth.js
  src/pages/signupPage/index.jsx
  src/utils/auth/constant.js
  src/utils/validate/signup.js
  yarn.lock
Labels: feature

#23 Feat/alarm popup menu
  package.json
  src/apis/alarm.js
  src/components/addPost/index.jsx
  src/components/alarm/AlarmPopup/index.jsx
  src/components/alarm/AlarmPopup/style.js
  src/components/alarm/AlarmPopupItem/index.jsx
  src/components/alarm/AlarmPopupItem/style.js
  src/components/alarm/index.jsx
  src/components/common/Avatar/index.jsx
  src/components/common/Button/index.js
  src/pages/Header/index.jsx
  src/pages/Header/style.js
Labels: feature

#28 Feat/logout
  src/Router.jsx
  src/components/Signin/Login.jsx
  src/pages/Header/index.jsx
Labels: feature

#30 Feat/post detail
  .gitignore
  package-lock.json
  package.json
  src/Router.jsx
  src/apis/alarm.js
  src/apis/comment.js
  src/apis/like.js
  src/apis/post.js
  src/components/ChannelList/index.jsx
  src/components/MainSection/Heart/index.jsx
  src/components/MainSection/Post/AuthorInfo/index.jsx
  src/components/MainSection/Post/AuthorInfo/style.js
  src/components/MainSection/Post/LeftImage/index.jsx
  src/components/MainSection/Post/LeftImage/style.js
  src/components/MainSection/Post/Tags/index.jsx
  src/components/MainSection/Post/Tags/style.js
  src/components/MainSection/Post/index.jsx
  src/components/MainSection/Post/style.js
  src/components/MainSection/PostDetail/Comment/index.jsx
  src/components/MainSection/PostDetail/Comment/style.js
  src/components/MainSection/PostDetail/Comments/index.jsx
  src/components/MainSection/PostDetail/Comments/style.js
  src/components/MainSection/PostDetail/index.jsx
  src/components/MainSection/PostDetail/style.js
  src/components/MainSection/index.jsx
  src/components/common/Image/index.jsx
  src/index.css
  src/pages/Header/index.jsx
  src/recoil/RecoilChannelState.js
  src/recoil/RecoilPostStates.js
  static/images/smile_emoji.png
Labels: feature, refactor

#32 Feat/createPostModal
  src/apis/core/index.js
  src/apis/post.js
  src/components/MainSection/index.jsx
  src/components/addPost/addPostForm/index.jsx
  src/components/addPost/addPostForm/style.js
  src/components/addPost/index.jsx
  src/components/addPost/style.js
  src/components/sidebarRIght/UserList/index.jsx
  src/pages/Header/index.jsx
  src/pages/HomePage/index.jsx
  src/recoil/addPostStates.js
  src/utils/imageConverter.js
Labels: feature, refactor

#35 Feat/main page init view
  src/components/ChannelList/SortedChannels/index.jsx
  src/components/ChannelList/SortedChannels/style.js
  src/components/ChannelList/index.jsx
  src/components/MainSection/Heart/index.jsx
  src/components/MainSection/Post/AuthorInfo/index.jsx
  src/components/MainSection/Post/index.jsx
  src/components/MainSection/PostDetail/Comments/index.jsx
  src/components/MainSection/index.jsx
  src/components/common/Skeleton/Card.jsx
  src/components/common/Skeleton/index.jsx
Labels: feature

#39 Refactor/sigin
  src/App.jsx
  src/Router.jsx
  src/apis/auth.js
  src/apis/core/index.js
  src/components/MainSection/index.jsx
  src/components/MyHome/index.jsx
  src/components/MyHome/style.js
  src/components/PersisteLogin/index.jsx
  src/components/RequireAuth/index.jsx
  src/components/Sidebar/index.jsx
  src/components/Sidebar/style.js
  src/hooks/useForm.js
  src/pages/Header/PrivateHeaderContainer/index.jsx
  src/pages/Header/index.jsx
  src/pages/MyPosterPage/index.jsx
  src/pages/MySettingPage/index.jsx
  src/pages/NotFound/index.jsx
Labels: refactor

#40 Feat/search post
  src/apis/core/index.js
  src/apis/search.js
  src/components/MainSection/index.jsx
  src/components/SearchPost/index.jsx
  src/components/SearchPost/style.js
  src/components/alarm/AlarmPopup/index.jsx
  src/components/alarm/AlarmPopup/style.js
  src/components/alarm/AlarmPopupItem/index.jsx
  src/pages/Header/index.jsx
  src/utils/validate/searchedPostLIst.js
Labels: feature

#43 Feat/sidebar desgin
  src/components/ChannelList/SortedChannels/index.jsx
  src/components/ChannelList/SortedChannels/style.js
  src/components/ChannelList/style.js
  src/components/MainSection/Post/AuthorInfo/index.jsx
  src/components/MainSection/Post/AuthorInfo/style.js
  src/components/MainSection/Post/LikeAndComment/index.jsx
  src/components/MainSection/Post/LikeAndComment/style.js
  src/components/MainSection/Post/index.jsx
  src/components/MainSection/Post/style.js
  src/components/MainSection/style.js
  src/components/Modal/style.js
  src/components/common/Avatar/index.jsx
  src/components/common/Skeleton/Card.jsx
  src/components/sidebarRIght/UserList/index.jsx
  src/components/sidebarRIght/UserList/style.js
  src/components/sidebarRIght/UserSearchBar/index.jsx
  src/components/sidebarRIght/UserSearchBar/style.js
  src/components/sidebarRIght/style.js
  src/index.css
Labels: fix, design

#57 Feat/post detail page
  src/Router.jsx
  src/components/ChannelList/SortedChannels/index.jsx
  src/components/ChannelList/index.jsx
  src/components/MainSection/Heart/index.jsx
  src/components/MainSection/PostDetail/Comments/index.jsx
  src/components/MainSection/PostDetail/index.jsx
  src/components/MainSection/index.jsx
  src/components/SearchPost/index.jsx
  src/components/alarm/AlarmPopup/index.jsx
  src/pages/Header/index.jsx
  src/pages/PostDetailPage/index.jsx
  src/pages/PostDetailPage/style.js
  src/recoil/channelState.js
  src/recoil/postStates.js
  src/recoil/toggleStates.js
Labels: feature, refactor

#63 Refactor/refactor main page
  src/components/ChannelList/SortedChannels/index.jsx
  src/components/MainSection/Heart/index.jsx
  src/components/MainSection/Heart/style.js
  src/components/MainSection/Post/LikeAndComment/index.jsx
  src/components/MainSection/Post/index.jsx
  src/components/MainSection/Post/style.js
  src/components/MainSection/PostDetail/Comments/index.jsx
  src/components/MainSection/PostDetail/index.jsx
  src/components/MainSection/PostDetail/style.js
  src/components/MainSection/index.jsx
  src/components/MainSection/style.js
  src/components/common/Skeleton/Detail.jsx
  src/components/common/Skeleton/index.jsx
  src/pages/Header/style.js
  src/pages/HomePage/style.js
  src/recoil/channelState.js
  src/recoil/tmp.js
Labels: refactor, style

#65 design: 메인 디자인 깨지는 부분 수정
  src/components/MainSection/PostDetail/Comments/style.js
  src/components/MainSection/PostDetail/style.js
  src/components/MainSection/style.js
  src/index.css
  src/pages/PostDetailPage/style.js
Labels: design

#67 Feat/not found
  src/components/MainSection/index.jsx
  src/components/MainSection/style.js
  src/pages/NotFound/index.jsx
  src/pages/NotFound/style.js
Labels: feature, style

#68 Feat/alarm skeleton
  src/components/alarm/index.jsx
  src/pages/Header/index.jsx
  src/pages/HomePage/index.jsx
Labels: refactor, fix

#73 fix: 알람 에러 수정
  package-lock.json
  src/components/MainSection/Heart/index.jsx
Labels: fix

#79 fix: undefined 타입 에러 수정
  src/components/MainSection/index.jsx
Labels: fix

#84 hotfix: 무한 요청 오류 수정
  src/components/MainSection/index.jsx
Labels: hotFix

#87 Fix/ 알람 오류 수정 및 private header 병합
  src/components/alarm/AlarmPopup/index.jsx
  src/components/alarm/AlarmPopupItem/index.jsx
  src/pages/Header/PrivateHeaderContainer/index.jsx
  src/pages/Header/index.jsx
Labels: refactor, fix

#89 Style/signup
  src/components/Signin/index.jsx
  src/components/Signup/index.jsx
  src/components/Signup/style.js
Labels: fix, style

#95 Refactor/user list hooks
  src/components/Signup/index.jsx
  src/components/Signup/style.js
  src/components/sidebarRIght/UserList/index.jsx
  src/components/sidebarRIght/UserList/style.js
  src/components/sidebarRIght/UserSearchBar/index.jsx
  src/hooks/useGetUserInfo.js
  src/hooks/useGetUserList.js
  src/hooks/useSignupForm.js
Labels: refactor, style, design

#96 Refactor/header refactoring
  src/components/MyHome/index.jsx
  src/components/Signin/index.jsx
  src/components/Signin/style.js
  src/components/alarm/AlarmPopup/index.jsx
  src/components/alarm/AlarmPopup/style.js
  src/components/alarm/AlarmPopupItem/index.jsx
  src/hooks/useAlarm.js
  src/hooks/useHeader.js
  src/pages/Header/index.jsx
  src/utils/validate/searchedPostLIst.js
Labels: feature, fix, design

#98 refactor: 훅분리
  src/components/ChannelList/index.jsx
  src/hooks/useChannel.js
Labels: refactor

#105 refactor: 포스트 검색 훅 분리 및 오류 해결
  src/apis/alarm.js
  src/apis/core/index.js
  src/components/SearchPost/index.jsx
  src/components/common/Avatar/index.jsx
  src/components/common/Image/index.jsx
  src/hooks/useMainSection.js
  src/hooks/useSearchPost.js
Labels: refactor, fix

#108 Design/fix css
  package-lock.json
  src/components/ChannelList/SortedChannels/style.js
  src/components/ChannelList/style.js
  src/components/MainSection/Like/index.jsx
  src/components/MainSection/Like/style.js
  src/components/MainSection/Post/AuthorInfo/style.js
  src/components/MainSection/Post/LikeAndComment/style.js
  src/components/MainSection/Post/Tags/style.js
  src/components/MainSection/Post/index.jsx
  src/components/MainSection/Post/style.js
  src/components/MainSection/PostDetail/Comment/style.js
  src/components/MainSection/PostDetail/style.js
  src/components/MainSection/style.js
  src/components/SearchPost/style.js
  src/components/Sidebar/index.jsx
  src/components/Sidebar/style.js
  src/components/common/Avatar/index.jsx
  src/components/sidebarRIght/UserList/style.js
  src/components/sidebarRIght/UserSearchBar/index.jsx
  src/components/sidebarRIght/UserSearchBar/style.js
  src/index.css
  src/pages/Header/index.jsx
  src/pages/Header/style.js
Labels: refactor, style

#110 Design/signin and signup
  src/components/Signin/index.jsx
  src/components/Signin/style.js
  src/components/Signup/index.jsx
  src/components/Signup/style.js
  src/index.css
Labels: refactor, design

#117 feat: 마이페이지 페이지네이션
  src/components/MyHome/UserInfo/index.jsx
  src/components/MyHome/UserInfo/style.js
  src/components/MyHome/UserPosteItem/index.jsx
  src/components/MyHome/UserPosteItem/style.js
  src/components/MyHome/UserPoster/index.jsx
  src/components/MyHome/style.js
  src/components/Pagination/index.js
  src/components/Pagination/style.js
  src/components/Sidebar/style.js
  src/components/Signin/style.js
  src/components/common/Avatar/index.jsx
  src/hooks/usePoster.js
  src/index.css
  src/pages/MyPosterPage/style.js
Labels: feature, design

#120 Fix/channel name
  src/components/ChannelList/index.jsx
  src/hooks/useChannel.js
  src/hooks/useMainSection.js
Labels: refactor, fix

#123 style: Edit Post Detail Modal Comment
  src/components/MainSection/PostDetail/Comments/style.js
  src/components/MainSection/PostDetail/style.js
Labels: style, design

#125 Build/vercel action
  .gitignore
  src/Router.jsx
  src/apis/core/index.js
  src/apis/post.js
  src/hooks/useMainSection.js
  src/pages/Header/index.jsx
  src/pages/HomePage/index.jsx
  src/utils/constant/post.js
Labels: build

#128 Feat/image compression
  package-lock.json
  package.json
  src/components/addPost/addPostForm/ErrorText/index.jsx
  src/components/common/Icons/Badge.js
  src/components/sidebarRIght/UserList/index.jsx
  src/components/sidebarRIght/UserList/style.js
  src/hooks/usePostForm.js
  src/pages/Header/index.jsx
  src/pages/Header/style.js
Labels: feature

#129 Fix/search title
  src/hooks/useSearchPost.js
  src/utils/post/constant.js
  src/utils/validate/searchedPostLIst.js
Labels: fix

#132 Feat/post validation
  src/hooks/usePostForm.js
  src/utils/constant/post.js
Labels: feature, refactor

#138 Style/myhome
  src/components/Modal/MyhomeModal/index.jsx
  src/components/Modal/MyhomeModal/style.js
  src/components/MyHome/UserPoster/index.jsx
  src/components/MyHome/UserPoster/style.js
  src/hooks/useMyHomeModal.js
Labels: refactor

#139 Fix/ Delete Comments
  src/apis/alarm.js
  src/apis/auth.js
  src/apis/comment.js
  src/apis/core/index.js
  src/apis/post.js
  src/apis/user.js
  src/components/Common/Avatar/index.jsx
  src/components/MyHome/UserPoster/index.jsx
  src/components/Pagination/index.js
Labels: fix

#140 Feat/grouping countries
  src/components/AddPost/AddPostForm/index.jsx
  src/hooks/usePostForm.js
  src/utils/constants/post.js
Labels: feature, refactor

#147 feat: 포스트 생성한 채널로 이동 기능 추가
  src/hooks/usePostForm.js
Labels: feature

#149 Feat/searh result data
  src/components/SearchPost/index.jsx
  src/components/SearchPost/style.js
  src/utils/validate/searchedPostLIst.js
Labels: feature, design

#155 Feat/channel create
  src/components/AddPost/AddPostForm/index.jsx
  src/hooks/useMainSection.js
  src/hooks/usePostForm.js
  src/recoil/channelState.js
Labels: feature
